Repository solvcon/devenv, pull requests merged in 2021-07, with the labels that each got.

#43 feat: bzip2 script enhance
  scripts/build.d/bzip2
Labels: enhancement

#50 Format the README style
  README.md
Labels: documentation

#55 feat(tests): add get_list unit tests
  tests/test_bash_utils.sh
Labels: testing

#54 Add unit tests for namemunge and nameremove in devenv_impl
  scripts/env.d/devenv_impl
  scripts/init
  tests/runner.sh
  tests/test_devenv_impl.sh
Labels: testing

#56 feat(cmd) Add a command to list all environments
  bin/devenv
  scripts/cmd.d/list
Labels: enhancement

#57 Make devenv function to print the active environment
  bin/devenv
  scripts/init
Labels: enhancement

#58 Update the build scripts up to numpy
  scripts/build.d/cython
  scripts/build.d/numpy
  scripts/build.d/openblas
  scripts/build.d/openssl
  scripts/build.d/python
  scripts/func.d/build_utils
Labels: enhancement

#61 Update README: add more documentation for installation and usage
  .gitmodules
  README.md
Labels: documentation

#63 Improve pybind11 build script
  scripts/build.d/pybind11
Labels: enhancement

#65 feat: enhance pip install sequence
  scripts/build.d/python
Labels: enhancement

#64 Run macos-10.15 unit test on Github action
  .github/workflows/shunit2_runner.yml
  tests/runner.sh
  tests/test_init_var.sh
Labels: testing
