Repository solvcon/devenv, pull requests merged in 2021-08, with the labels that each got.

#70 bug_fix: fixed list return value
  scripts/cmd.d/list
Labels: fix

#69 Add "DEVENVALIAS" variable to create an alias to "devenv" driver command
  scripts/init
Labels: enhancement

#72 Add usage of show
  bin/devenv
Labels: enhancement

#73 Add usage of show in README.md
  README.md
Labels: documentation

#75 [build/numpy] Add --old-and-unmanageable
  scripts/build.d/numpy
Labels: enhancement

#74 [feature] Add DEVENVCURRENTROOT environment variable
  README.md
  bin/devenv
  scripts/env.d/vars
  scripts/init
Labels: enhancement

#77 Change to build script (netcdf and gnu make)
  scripts/build.d/make
  scripts/build.d/netcdf
Labels: enhancement

#76 Set DEVENVCURRENTROOT back to /dev/null after devenv off
  .gitignore
  scripts/env.d/vars
  scripts/init
  tests/test_bash_utils.sh
  tests/test_devenv_impl.sh
  tests/test_init_var.sh
Labels: bug
